<?php

namespace Innov\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentClicheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentClicheRepository extends EntityRepository
{
}
