<?php

namespace Innov\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousDossierPersoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousDossierPersoRepository extends EntityRepository
{
    public function filtrerParDossierEtNom($dossierPerso, $nom)
	{
		$qb = $this->createQueryBuilder('s');
		$qb->where('s.dossierPerso = :dossierPerso ')
		->setParameter('dossierPerso', $dossierPerso)
		->andWhere('s.nom = :nom')
		->setParameter('nom', $nom);
		return $qb->getQuery()->getSingleResult();
	}
        
   
}
