<?php

namespace Innov\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
        public function filtrerTag($query)
   {
       $qb = $this->createQueryBuilder('t');
		$qb->where('t.text LIKE :query ')
		->setParameter('query',$query.'%');
		return $qb->getQuery()->getResult();
   }
}
