security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false
        main:
            pattern: .*
            form_login:
                provider:             fos_userbundle
                csrf_provider:        form.csrf_provider
                check_path:           fos_user_security_check
                login_path:           fos_user_security_login
                use_forward:          false
                failure_path:         null
                default_target_path:  InnovGroup_index
                remember_me:          true
            logout:       
              path:       fos_user_security_logout
              target:     InnovGroup_index   
                
            remember_me:  
                key:      %secret%
                lifetime: 300000000000000
                path:     /
                domain:   ~
            
            anonymous:    true