<?php

namespace Innov\GroupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupMembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupMembreRepository extends EntityRepository
{
    public function checkStatut($user,$groupe)
	{
		$qb = $this->createQueryBuilder('gm');
		$qb->where('gm.user = :user ')
		->setParameter('user', $user)
		->andWhere('gm.groupe = :groupe')
		->setParameter('groupe', $groupe);
		return $qb->getQuery()->getOneOrNullResult();
	}

	

}
