<?php

namespace Proxies\__CG__\Innov\GroupBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Groupe extends \Innov\GroupBundle\Entity\Groupe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'idSolr', 'nom', 'dateCreation', 'membres', 'notif', 'examCollections');
        }

        return array('__isInitialized__', 'id', 'idSolr', 'nom', 'dateCreation', 'membres', 'notif', 'examCollections');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Groupe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', array($dateCreation));

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', array());

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function addMembre(\Innov\UserBundle\Entity\User $membres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMembre', array($membres));

        return parent::addMembre($membres);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMembre(\Innov\UserBundle\Entity\User $membres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMembre', array($membres));

        return parent::removeMembre($membres);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembres', array());

        return parent::getMembres();
    }

    /**
     * {@inheritDoc}
     */
    public function addNotif(\Innov\UserBundle\Entity\Notification $notif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNotif', array($notif));

        return parent::addNotif($notif);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNotif(\Innov\UserBundle\Entity\Notification $notif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNotif', array($notif));

        return parent::removeNotif($notif);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotif', array());

        return parent::getNotif();
    }

    /**
     * {@inheritDoc}
     */
    public function addExamCollection(\Innov\GroupBundle\Entity\ExamCollection $examCollections)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExamCollection', array($examCollections));

        return parent::addExamCollection($examCollections);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExamCollection(\Innov\GroupBundle\Entity\ExamCollection $examCollections)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExamCollection', array($examCollections));

        return parent::removeExamCollection($examCollections);
    }

    /**
     * {@inheritDoc}
     */
    public function getExamCollections()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExamCollections', array());

        return parent::getExamCollections();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSolr($idSolr = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSolr', array($idSolr));

        return parent::setIdSolr($idSolr);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSolr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSolr', array());

        return parent::getIdSolr();
    }

}
